### ISSUE TITLE
Article Listing page

### ISSUE THREAD

**Issue by swilgosz** [driggl/blog-next#7]
# Overview

Add a blog listing page with infinity scroll hooked up.

**Page URL:** `/blog`
** API URL: ** `env.API_URL/articles`

`ENV['API_URL'] = 'https://api.sourcerio.com/blogging/v1/blogs/driggl`

### Todo

Suggested Material UI components: Cards

- [x] Thumbnails and article's details
- [x] Links To single article ( `/blog/a/_slug`)
- [x] Infinity Loading
- [x] SEO-Friendly. Meta Tags
- [x] SEO-Friendly. Allow to load multiple pages of articles.

**Loading multiple pages of articles.**
- `http://localhost:3000/blog` should list first 10 articles.

`http://localhost:3000/blog?page=2` should list  10 articles from the second page (starting from 11th)

**Meta Tags**

```javascript
  head: {
    title: "Recent Articles",
    titleTemplate: "%s | Driggl - Modern web development",
    meta: [
      {
        hid: "description",
        name: "description",
        content:
          "Build modern websites like a professional with Driggl's Community!",
        titleTemplate: null,
      },
      {
        hid: "author",
        name: "author",
        content: "Driggl - https://driggl.com",
      },
      {
        property: "og:title",
        content: "Recent articles",
        vmid: "og:title",
      },
      {
        property: "og:description",
        content:
          "Newest content from web Professionals and the Modern web development Community!",
        vmid: "og:description",
      },
      {
        property: "og:image",
        content: "/home-cover.jpg",
        vmid: "og:image",
      },
      {
        property: "og:type",
        content: "website",
      },
    ],
  },
```
