### ISSUE TITLE
Article's Details Page

### ISSUE THREAD

**Issue by swilgosz** [driggl/blog-next#8]
### Overview

Add an article's detail page, where people can see the full content and comment it out.

### Todo

- [x] Show article meta information (Author, category, title, Cover Image)
- [x] Show Article's HTML content
- [x] Show Code Snippets in the Highlighted form
- [x] Allow to replace keywords with dynamic React Components
- [x] SEO-Friendly - Meta information
- [x] Content loaded via SSR

**Dynamic react components**

```javascript
html = html
        .replace("{{", "<span>{</span><span>{</span>")
        .replace("}}", "<span>}</span><span>}</span>")
        .replace(
          "<p>[[EmailSubscriptionForm]]</p>",
          "<EmailSubscriptionForm />"
        )
        .replace(
          "<p>[[CourseAdAPI]]</p>",
          '<CourseAd :size="size" :bg="adBgColor" />'
        );
```

**Code snippet example**

API delivers information about The snippet title and the language in the first line. The format is: 

`# <<Language>>: <<Title>>`

Example:

```shell
# shell: Logs for loading encrypted events
irb(main):105:0> list = UserList::Retriever.new(
  event_store: Sourcer::Container['event_store']
)
irb(main):106:0> list.retrieve.users
```

It would be nice to have it formatted in the way, the code highlighting engine takes care about the `<<Language>>` and shows the snippet title in the nicely formatted way at the top of every snippet. Example: 

![image](https://user-images.githubusercontent.com/8088317/114020390-d65ad180-986f-11eb-926d-6eca9fca47b9.png)

**HTML Head Meta tags**

```javascript
  head() {
    return {
      title: this.selected.attributes.title,
      // titleTemplate: " %s | Driggl - Modern web development",
      meta: [
        {
          name: "twitter:site",
          content: "@drigglweb"
        },
        {
          name: "twitter:card",
          content: "summary_large_image"
        },
        {
          name: "twitter:creator",
          content: "@sebwilgosz"
        },
        {
          name: "twitter:title",
          content: this.selected.attributes.title
        },
        {
          name: "twitter:description",
          content: this.selected.attributes.excerpt
        },
        {
          name: "twitter:image",
          content: this.selected.attributes.thumbnail.sharing
        },
        {
          hid: "description",
          name: "description",
          content: this.selected.attributes.excerpt
        },
        {
          property: "og:title",
          content: this.selected.attributes.title
        },
        {
          property: "og:description",
          content: this.selected.attributes.excerpt
        },
        {
          property: "og:image",
          content: this.selected.attributes.thumbnail.sharing
        },
        {
          property: "og:image:width",
          content: 1200
        },
        {
          property: "og:image:height",
          content: 630
        },
        // {
        //   property: "og:url",
        //   content: "https://driggl.com" + this.$route.path
        // },
        {
          property: "og:type",
          content: "article"
        },
        {
          property: "fb:app_id",
          content: process.env.FB_APP_ID
        },
        {
          property: "article:author",
          content: "https://www.facebook.com/sebastian.wilgosz"
        },
        {
          property: "article:publisher",
          content: "https://www.facebook.com/driggl"
        },
        {
          property: "og:site_name",
          content: "Driggl - Modern Web Development"
        },
        {
          name: "author",
          content: "Sebastian Wilgosz"
        }
      ]
    };
  },
```

### Screenshots for reference

![image](https://user-images.githubusercontent.com/8088317/113460815-45709a00-941a-11eb-84c0-845efa96b988.png)

![image](https://user-images.githubusercontent.com/8088317/113460872-79e45600-941a-11eb-8f16-4cea6d18430d.png)

![image](https://user-images.githubusercontent.com/8088317/113460888-8d8fbc80-941a-11eb-9e44-667c346d8abc.png)

### Dev notes

- [Vue implementation for a reference](https://github.com/driggl/blog/blob/master/pages/blog/a/_id.vue)

**Comment by swilgosz** [comment]
@adamszwaba I've added an example with a screenshot for code snippets
